In [1]:
words = open('names.txt', 'r').read().splitlines()

In [2]:
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [3]:
len(words)

32033

In [4]:
min(len(w) for w in words)

2

In [5]:
max(len(w) for w in words)

15

In [6]:
for w in words[:1]:
    for ch1, ch2 in zip(w, w[1:]):
        print(ch1, ch2)

e m
m m
m a


In [7]:
for w in zip(words[1], words[1][1:]):
    print(w)

('o', 'l')
('l', 'i')
('i', 'v')
('v', 'i')
('i', 'a')


In [8]:
for w in words[:1]:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]):
        print(ch1, ch2)

<S> e
e m
m m
m a
a <E>


In [9]:
for w in words[:3]:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]):
        print(ch1, ch2)

<S> e
e m
m m
m a
a <E>
<S> o
o l
l i
i v
v i
i a
a <E>
<S> a
a v
v a
a <E>


In [10]:
b = {}

for w in words[:3]:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]):
        bigram = (ch1, ch2)
        b[bigram] = b.get(bigram, 0) + 1

b

{('<S>', 'e'): 1,
 ('e', 'm'): 1,
 ('m', 'm'): 1,
 ('m', 'a'): 1,
 ('a', '<E>'): 3,
 ('<S>', 'o'): 1,
 ('o', 'l'): 1,
 ('l', 'i'): 1,
 ('i', 'v'): 1,
 ('v', 'i'): 1,
 ('i', 'a'): 1,
 ('<S>', 'a'): 1,
 ('a', 'v'): 1,
 ('v', 'a'): 1}

In [11]:
b = {}

for w in words:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]):
        bigram = (ch1, ch2)
        b[bigram] = b.get(bigram, 0) + 1
b

{('<S>', 'e'): 1531,
 ('e', 'm'): 769,
 ('m', 'm'): 168,
 ('m', 'a'): 2590,
 ('a', '<E>'): 6640,
 ('<S>', 'o'): 394,
 ('o', 'l'): 619,
 ('l', 'i'): 2480,
 ('i', 'v'): 269,
 ('v', 'i'): 911,
 ('i', 'a'): 2445,
 ('<S>', 'a'): 4410,
 ('a', 'v'): 834,
 ('v', 'a'): 642,
 ('<S>', 'i'): 591,
 ('i', 's'): 1316,
 ('s', 'a'): 1201,
 ('a', 'b'): 541,
 ('b', 'e'): 655,
 ('e', 'l'): 3248,
 ('l', 'l'): 1345,
 ('l', 'a'): 2623,
 ('<S>', 's'): 2055,
 ('s', 'o'): 531,
 ('o', 'p'): 95,
 ('p', 'h'): 204,
 ('h', 'i'): 729,
 ('<S>', 'c'): 1542,
 ('c', 'h'): 664,
 ('h', 'a'): 2244,
 ('a', 'r'): 3264,
 ('r', 'l'): 413,
 ('l', 'o'): 692,
 ('o', 't'): 118,
 ('t', 't'): 374,
 ('t', 'e'): 716,
 ('e', '<E>'): 3983,
 ('<S>', 'm'): 2538,
 ('m', 'i'): 1256,
 ('a', 'm'): 1634,
 ('m', 'e'): 818,
 ('<S>', 'h'): 874,
 ('r', 'p'): 14,
 ('p', 'e'): 197,
 ('e', 'r'): 1958,
 ('r', '<E>'): 1377,
 ('e', 'v'): 463,
 ('v', 'e'): 568,
 ('l', 'y'): 1588,
 ('y', 'n'): 1826,
 ('n', '<E>'): 6763,
 ('b', 'i'): 217,
 ('i', 'g'): 428,


In [12]:
b.items()

dict_items([(('<S>', 'e'), 1531), (('e', 'm'), 769), (('m', 'm'), 168), (('m', 'a'), 2590), (('a', '<E>'), 6640), (('<S>', 'o'), 394), (('o', 'l'), 619), (('l', 'i'), 2480), (('i', 'v'), 269), (('v', 'i'), 911), (('i', 'a'), 2445), (('<S>', 'a'), 4410), (('a', 'v'), 834), (('v', 'a'), 642), (('<S>', 'i'), 591), (('i', 's'), 1316), (('s', 'a'), 1201), (('a', 'b'), 541), (('b', 'e'), 655), (('e', 'l'), 3248), (('l', 'l'), 1345), (('l', 'a'), 2623), (('<S>', 's'), 2055), (('s', 'o'), 531), (('o', 'p'), 95), (('p', 'h'), 204), (('h', 'i'), 729), (('<S>', 'c'), 1542), (('c', 'h'), 664), (('h', 'a'), 2244), (('a', 'r'), 3264), (('r', 'l'), 413), (('l', 'o'), 692), (('o', 't'), 118), (('t', 't'), 374), (('t', 'e'), 716), (('e', '<E>'), 3983), (('<S>', 'm'), 2538), (('m', 'i'), 1256), (('a', 'm'), 1634), (('m', 'e'), 818), (('<S>', 'h'), 874), (('r', 'p'), 14), (('p', 'e'), 197), (('e', 'r'), 1958), (('r', '<E>'), 1377), (('e', 'v'), 463), (('v', 'e'), 568), (('l', 'y'), 1588), (('y', 'n'), 18

In [13]:
sorted(b.items(), key = lambda kv: -kv[1])

[(('n', '<E>'), 6763),
 (('a', '<E>'), 6640),
 (('a', 'n'), 5438),
 (('<S>', 'a'), 4410),
 (('e', '<E>'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('<S>', 'k'), 2963),
 (('l', 'e'), 2921),
 (('e', 'n'), 2675),
 (('l', 'a'), 2623),
 (('m', 'a'), 2590),
 (('<S>', 'm'), 2538),
 (('a', 'l'), 2528),
 (('i', '<E>'), 2489),
 (('l', 'i'), 2480),
 (('i', 'a'), 2445),
 (('<S>', 'j'), 2422),
 (('o', 'n'), 2411),
 (('h', '<E>'), 2409),
 (('r', 'a'), 2356),
 (('a', 'h'), 2332),
 (('h', 'a'), 2244),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('<S>', 's'), 2055),
 (('a', 'y'), 2050),
 (('y', '<E>'), 2007),
 (('e', 'r'), 1958),
 (('n', 'n'), 1906),
 (('y', 'n'), 1826),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1697),
 (('<S>', 'd'), 1690),
 (('i', 'e'), 1653),
 (('a', 'i'), 1650),
 (('<S>', 'r'), 1639),
 (('a', 'm'), 1634),
 (('l', 'y'), 1588),
 (('<S>', 'l'), 1572),
 (('<S>', 'c'), 1542),
 (('<S>', 'e'), 1531),
 (('j', 'a'), 1473),
 (

In [14]:
import torch

In [15]:
a = torch.zeros((3, 5), dtype=torch.int32)
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [16]:
a.dtype

torch.int32

In [17]:
a[1, 3] = 1
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [18]:
a[0, 0] = 5
a

tensor([[5, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [19]:
N = torch.zeros((28, 28), dtype=torch.int32)

In [20]:
set(''.join(words))

{'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z'}

In [21]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i for i, s in enumerate(chars)}
stoi['<S>'] = 26
stoi['<E>'] = 27

In [22]:
for w in words:
    chs = ['<S>'] + list(w) + ['<E>']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1

In [23]:
itos = {i:s for s,i in stoi.items()}

In [24]:
type(N[0, 3])

torch.Tensor

In [25]:
type(N[0, 3].item())

int

In [26]:
N[0, 3]

tensor(1042, dtype=torch.int32)

In [27]:
N[0, 3].item()

1042

In [28]:
import matplotlib.pyplot as plt
%matplotlib inline

# plt.figure(figsize=(16,16))
# plt.imshow(N, chmap='Blues')
# for i in range(28):
#     for j in range(28):
#         chstr = itos[i] + itos[j]
#         plt.text(j, i, chstr, ha="center", va="bottom", color="gray")
#         plt.text(j, i, N[i, j].item(), ha="center", va="top", color="gray")
# plt.axis("off")

In [29]:
N = torch.zeros((27, 27), dtype=torch.int32)

chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0

itos = {i:s for s,i in stoi.items()}

for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        N[ix1, ix2] += 1

In [30]:
N[0, :]

tensor([   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
        1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
         134,  535,  929], dtype=torch.int32)

In [31]:
N[0, :].shape

torch.Size([27])

In [32]:
N[0]

tensor([   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
        1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
         134,  535,  929], dtype=torch.int32)

In [33]:
p = N[0].float()
p

tensor([   0., 4410., 1306., 1542., 1690., 1531.,  417.,  669.,  874.,  591.,
        2422., 2963., 1572., 2538., 1146.,  394.,  515.,   92., 1639., 2055.,
        1308.,   78.,  376.,  307.,  134.,  535.,  929.])

In [34]:
p = N[0].float()
p = p / p.sum()
p

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])

In [35]:
p.sum()

tensor(1.)

In [36]:
g = torch.Generator().manual_seed(2147483647)
p1 = torch.rand(3, generator=g)
p1 = p1 / p1.sum()

In [37]:
p1

tensor([0.6064, 0.3033, 0.0903])

In [38]:
p1.sum()

tensor(1.)

In [39]:
torch.multinomial(p1, num_samples=20, replacement=True, generator=g)

tensor([1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1])

In [40]:
g = torch.Generator().manual_seed(2147483647)
ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
ix

3

In [41]:
itos[ix]

'c'

In [42]:
g = torch.Generator().manual_seed(2147483647)

ix = 0
while True:
    p = N[ix].float()
    p = p / p.sum()
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    if ix == 0:
        break
    print(itos[ix])
    

c
e
x
z
e


In [43]:
g = torch.Generator().manual_seed(2147483647)

out = []
ix = 0
while True:
    p = N[ix].float()
    p = p / p.sum()
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    if ix == 0:
        break
    out.append(itos[ix])

name = ''.join(out)
print(name)

cexze


In [44]:
def generate_name():
    out = []
    ix = 0
    while True:
        p = N[ix].float()
        p = p / p.sum()
        ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
        if ix == 0:
            break
        out.append(itos[ix])

    name = ''.join(out)
    return name

for i in range(10):
    print(generate_name())

momasurailezitynn
konimittain
llayn
ka
da
staiyaubrtthrigotai
moliellavo
ke
teda
ka


In [45]:
g = torch.Generator().manual_seed(2147483647)

out = []
ix = 0
while True:
    
    #p = N[ix].float()
    #p = p / p.sum()

    # Sample from uniform distribution
    p = torch.ones(27) / 27.0

    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    if ix == 0:
        break
    out.append(itos[ix])

name = ''.join(out)
print(name)

cexzm


In [46]:
P = N.float()
P.shape

torch.Size([27, 27])

In [47]:
P.sum(1, keepdim=True).shape

torch.Size([27, 1])

In [48]:
P = N.float()
P /= P.sum(1, keepdim=True)
P.shape

torch.Size([27, 27])

In [49]:
P[0].sum()

tensor(1.)

In [50]:
g = torch.Generator().manual_seed(2147483647)

out = []
ix = 0
while True:
    p = P[ix]
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    if ix == 0:
        break
    out.append(itos[ix])

name = ''.join(out)
print(name)

cexze


In [51]:
for w in words[:3]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1, ix2]
        print(f"{ch1}{ch2}: {prob:.4f}")

.e: 0.0478
em: 0.0377
mm: 0.0253
ma: 0.3899
a.: 0.1960
.o: 0.0123
ol: 0.0780
li: 0.1777
iv: 0.0152
vi: 0.3541
ia: 0.1381
a.: 0.1960
.a: 0.1377
av: 0.0246
va: 0.2495
a.: 0.1960


In [52]:
# Likelihood: product of the probabilities
# Try to get it as high as possible.
# Bad stuff to handle: product of numbers in [0, 1].
# Use log likelihood

for w in words[:3]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1, ix2]
        logprob = torch.log(prob)
        print(f"{ch1}{ch2}: {logprob:.4f}")

.e: -3.0408
em: -3.2793
mm: -3.6772
ma: -0.9418
a.: -1.6299
.o: -4.3982
ol: -2.5508
li: -1.7278
iv: -4.1867
vi: -1.0383
ia: -1.9796
a.: -1.6299
.a: -1.9829
av: -3.7045
va: -1.3882
a.: -1.6299


In [53]:
# log(a*b*c) = log(a) + log(b) + log(c)
log_likelihood = 0.0
for w in words[:3]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob

print(f"{log_likelihood=}")

log_likelihood=tensor(-38.7856)


In [54]:
# loss function: low is good. semantics
# log likelihood is not a loss function

nll = - log_likelihood
print(f"{nll=}")

nll=tensor(38.7856)


In [55]:
# people also normalize
n = 0
log_likelihood = 0.0
for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1
avg_nll = - log_likelihood / n
print(f"{avg_nll=}")

avg_nll=tensor(2.4541)


In [56]:
n = 0
log_likelihood = 0.0
for w in ["andrejq"]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1
        print(f"{ch1}{ch2}: {prob:4f}")
avg_nll = - log_likelihood / n
print(f"{avg_nll=}")

.a: 0.137671
an: 0.160484
nd: 0.038413
dr: 0.077147
re: 0.133622
ej: 0.002693
jq: 0.000000
q.: 0.102941
avg_nll=tensor(inf)


In [57]:
# Model smoothing
P = (N + 1).float()
P /= P.sum(1, keepdim=True)

In [58]:
n = 0
log_likelihood = 0.0
for w in ["andrejq"]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        prob = P[ix1, ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n += 1
        print(f"{ch1}{ch2}: {prob:4f}")
avg_nll = - log_likelihood / n
print(f"{avg_nll=}")

.a: 0.137586
an: 0.160386
nd: 0.038411
dr: 0.076951
re: 0.133417
ej: 0.002738
jq: 0.000342
q.: 0.096990
avg_nll=tensor(3.4834)


In [59]:
# create the training set of the bigrams

xs, ys = [], []

# example, one word
for w in words[:1]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        print(ch1, ch2)
        xs.append(ix1)
        ys.append(ix2)

xs = torch.tensor(xs)
ys = torch.tensor(ys)

. e
e m
m m
m a
a .


In [60]:
xs

tensor([ 0,  5, 13, 13,  1])

In [61]:
ys

tensor([ 5, 13, 13,  1,  0])

In [62]:
xs, ys = [], []

for w in words:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        print(ch1, ch2)
        xs.append(ix1)
        ys.append(ix2)

xs = torch.tensor(xs)
ys = torch.tensor(ys)

. e
e m
m m
m a
a .
. o
o l
l i
i v
v i
i a
a .
. a
a v
v a
a .
. i
i s
s a
a b
b e
e l
l l
l a
a .
. s
s o
o p
p h
h i
i a
a .
. c
c h
h a
a r
r l
l o
o t
t t
t e
e .
. m
m i
i a
a .
. a
a m
m e
e l
l i
i a
a .
. h
h a
a r
r p
p e
e r
r .
. e
e v
v e
e l
l y
y n
n .
. a
a b
b i
i g
g a
a i
i l
l .
. e
e m
m i
i l
l y
y .
. e
e l
l i
i z
z a
a b
b e
e t
t h
h .
. m
m i
i l
l a
a .
. e
e l
l l
l a
a .
. a
a v
v e
e r
r y
y .
. s
s o
o f
f i
i a
a .
. c
c a
a m
m i
i l
l a
a .
. a
a r
r i
i a
a .
. s
s c
c a
a r
r l
l e
e t
t t
t .
. v
v i
i c
c t
t o
o r
r i
i a
a .
. m
m a
a d
d i
i s
s o
o n
n .
. l
l u
u n
n a
a .
. g
g r
r a
a c
c e
e .
. c
c h
h l
l o
o e
e .
. p
p e
e n
n e
e l
l o
o p
p e
e .
. l
l a
a y
y l
l a
a .
. r
r i
i l
l e
e y
y .
. z
z o
o e
e y
y .
. n
n o
o r
r a
a .
. l
l i
i l
l y
y .
. e
e l
l e
e a
a n
n o
o r
r .
. h
h a
a n
n n
n a
a h
h .
. l
l i
i l
l l
l i
i a
a n
n .
. a
a d
d d
d i
i s
s o
o n
n .
. a
a u
u b
b r
r e
e y
y .
. e
e l
l l
l i
i e
e .
. s
s t


In [63]:
# one hot encoding: 3 -> (0,0,1); 2 -> (0,1,0) with dim 3

import torch.nn.functional as F 
xenc = F.one_hot(xs, num_classes=27)
xenc

tensor([[1, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 1, 0],
        [0, 0, 0,  ..., 0, 0, 1],
        [0, 0, 0,  ..., 1, 0, 0]])

In [64]:
xenc.shape

torch.Size([228146, 27])

In [65]:
xenc.dtype

torch.int64

In [66]:
# we want floats for neural nets
xenc = xenc.float()

In [67]:
xenc.dtype

torch.float32

In [68]:
# weights for a single neuron
W = torch.randn((27, 1))
W

tensor([[ 0.0150],
        [ 0.6600],
        [ 1.6905],
        [-1.2057],
        [ 0.7637],
        [-0.8019],
        [ 1.6045],
        [-2.1915],
        [ 1.1094],
        [-1.0434],
        [-0.3569],
        [-0.0310],
        [-0.2917],
        [-1.3093],
        [-0.0999],
        [-0.5884],
        [ 0.0595],
        [-1.2187],
        [-1.4520],
        [ 0.2425],
        [-0.2479],
        [ 0.2067],
        [-1.2948],
        [-0.3538],
        [ 0.4934],
        [-1.1943],
        [-1.6112]])

In [69]:
# matrix multiplication
# (5, 27) @ (27, 1) = (5, 1)
xenc @ W

tensor([[ 0.0150],
        [-0.8019],
        [-1.3093],
        ...,
        [-1.1943],
        [-1.6112],
        [ 0.4934]])

In [70]:
# weights for 27 neurons
W = torch.randn((27, 27))
xenc @ W

tensor([[ 0.7252,  1.7700, -1.8705,  ...,  0.1620,  0.2387,  0.5883],
        [ 1.3311, -0.9795, -0.1635,  ..., -0.9732, -0.8560, -0.5166],
        [-1.0510, -0.9463,  0.9942,  ..., -0.5760,  1.2579,  0.6392],
        ...,
        [-0.8440,  0.9012, -0.7891,  ..., -0.8951,  0.4116, -0.1381],
        [ 1.2725, -1.0828, -0.5367,  ...,  0.1329, -0.9937,  0.2407],
        [-0.5369, -1.5028, -0.6489,  ...,  1.5164, -0.3935,  1.8251]])

In [71]:
# dot product
(xenc[3] * W[:, 13]).sum()

tensor(-0.8486)

In [72]:
(xenc @ W)[3, 13]

tensor(-0.8486)

The network outputs log counts, to get the counts, we need to exponentiate.

In [73]:
(xenc @ W).exp()

tensor([[2.0651, 5.8709, 0.1540,  ..., 1.1758, 1.2696, 1.8009],
        [3.7852, 0.3755, 0.8492,  ..., 0.3779, 0.4249, 0.5966],
        [0.3496, 0.3882, 2.7025,  ..., 0.5621, 3.5181, 1.8950],
        ...,
        [0.4300, 2.4626, 0.4542,  ..., 0.4085, 1.5093, 0.8711],
        [3.5698, 0.3386, 0.5847,  ..., 1.1421, 0.3702, 1.2721],
        [0.5845, 0.2225, 0.5226,  ..., 4.5558, 0.6747, 6.2031]])

In [74]:
logits = xenc @ W # log-counts
counts = logits.exp() # role of N 
probs = counts / counts.sum(1, keepdims=True)
probs

tensor([[0.0380, 0.1079, 0.0028,  ..., 0.0216, 0.0233, 0.0331],
        [0.0865, 0.0086, 0.0194,  ..., 0.0086, 0.0097, 0.0136],
        [0.0098, 0.0109, 0.0757,  ..., 0.0157, 0.0985, 0.0531],
        ...,
        [0.0098, 0.0559, 0.0103,  ..., 0.0093, 0.0343, 0.0198],
        [0.0592, 0.0056, 0.0097,  ..., 0.0189, 0.0061, 0.0211],
        [0.0093, 0.0035, 0.0083,  ..., 0.0723, 0.0107, 0.0985]])

In [75]:
probs[0].sum()

tensor(1.0000)

In [77]:
probs[0].shape

torch.Size([27])

In [76]:
probs.shape

torch.Size([228146, 27])

In [78]:
def logmax(logits):
    counts = logits.exp() 
    probs = counts / counts.sum(1, keepdims=True)
    return probs

In [81]:
nlls = torch.zeros(5)

for i in range(5):
    x = xs[i].item()
    y = ys[i].item()
    print("----------")
    print(f"Bigram example {i+1}: {itos[x]}{itos[y]} (indexes {x}, {y})")
    print("Input to the neural net:", x)
    print("Output probabilities from the neural net:", probs[i])
    print("Label (actual next character):", y)
    p = probs[i, y]
    print("Probability assigned by the net to the correct character:", p.item())
    logp = torch.log(p)
    print("Log likelyhood:", logp.item())
    nll = -logp
    print("Negative likelihood:", nll.item())
    nlls[i] = nll

print("==========")
print("Average negative log likelyhood (loss):", nlls.mean().item())

----------
Bigram example 1: .e (indexes 0, 5)
Input to the neural net: 0
Output probabilities from the neural net: tensor([0.0380, 0.1079, 0.0028, 0.0170, 0.0066, 0.0155, 0.3189, 0.0053, 0.0522,
        0.0071, 0.0494, 0.0060, 0.0163, 0.0190, 0.0338, 0.0262, 0.0655, 0.0060,
        0.0271, 0.0508, 0.0056, 0.0297, 0.0070, 0.0082, 0.0216, 0.0233, 0.0331])
Label (actual next character): 5
Probability assigned by the net to the correct character: 0.015531499870121479
Log likelyhood: -4.1648850440979
Negative likelihood: 4.1648850440979
----------
Bigram example 2: em (indexes 5, 13)
Input to the neural net: 5
Output probabilities from the neural net: tensor([0.0865, 0.0086, 0.0194, 0.0504, 0.0566, 0.0553, 0.0145, 0.0145, 0.0096,
        0.0052, 0.0228, 0.0060, 0.3035, 0.0145, 0.0118, 0.0144, 0.0854, 0.0050,
        0.0111, 0.0788, 0.0244, 0.0145, 0.0537, 0.0013, 0.0086, 0.0097, 0.0136])
Label (actual next character): 13
Probability assigned by the net to the correct character: 0.014482561